sources:
  - Brawler.glyphs
outputDir: "../fonts"
buildStatic: true
buildVariable: true
buildTTF: true
buildOTF: true
buildWebfont: true
axisOrder:
  - wght
stat:
  Brawler[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700